#server:
#    servlet:
#        context-path: /study

#Slf4j 로깅레벨 : TRACE > DEBUG > INFO > WARN > ERROR > FATAL
spring:
  datasource:
    url: jdbc:log4jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    #driver-class-name: org.h2.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    hibernate:
      ddl-auto: create # 운영환경에서는 none으로 설정
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
      #hibernate.format_sql : true
logging:
  level:
    jocture:
      todo: DEBUG
    org.hibernate:
      SQL: DEBUG
      type: TRACE
      type.BasicTypeRegistry: INFO
    jdbc:
      resultset: OFF


